### ISSUE TITLE
Potential author list updates for CWP doc

### ISSUE THREAD

**Issue by davidlange6** [HEP-SF/documents#48]
we asked for and got some feedback by checking the reco-trigger author list - these changes might be of interest for the full CWP list as well

EPFL: Institute of Physics, École Polytechnique F\'ed\'erale de Lausanne (EPFL), Lausanne, Switzerland

ETHZurich: ETH Z\"urich - Institute for Particle Physics and Astrophysics (IPA), Z\"urich, Switzerland

LMU: Fakult\"at f\"ur Physik, Ludwig-Maximilians-Universit\"at M\"unchen, M\"unchen, Germany

MIT: Laboratory for Nuclear Science, Massachusetts Institute of Technology, Cambridge, MA, USA
(MIT is different from UMass)

at least some NIKHEF authors are affiliated with Vrije university not university of Amsterdam (ymmv here)
NIKHEF: Nikhef National Institute for Subatomic Physics and Vrije Universiteit Amsterdam, Amsterdam, The Netherlands

UZurich: Physik-Institut, Universit\"at Z\"urich, Z\"urich, Switzerland

**Comment by graeme-a-stewart** [comment]
Interesting - we took the institutes' addresses from experiment papers, though even here there was not complete consistency. It's probably a matter of contacting those who are signers for a particular institute and asking them to decide (collectively) if they want to change it.

**Comment by davidlange6** [comment]
Indeed, we contacted everyone on our list and got these feedbacks - the accents were all correctly done in the txt but not translated properly into latexize.. For MIT the address was of the wrong institute. For Nikhef, I guess it might be more complicated..

**Comment by eduardo-rodrigues** [comment]
Hi all, from a quick-ish check I only see a due update for MIT, which in the file authors/address.txt gives what should rather be UMass, as mentioned by David. The rest is what we have.
Note that you probably mention MIT for Mike Williams, and that's indeed correct. The one person in the CWP that is linked to the "MIT" tag might well be from the University of Massachusetts, in which case its address is actually correct in spite of the misleading tag. To be confirmed ...

**Comment by jouvin** [comment]
Remember that tags are used only for internal references and not exported at any time. So the most important is that the author and the organisation linked are correct. But better to fix misleading tags, I agree...

**Comment by jouvin** [comment]
The original issue probably requires a fix in the script used to generate the latex from the text files... I think that it was right originally but at the very end we had to switch from pdflatex to another latex processor which was handling UTF-8 properly but this may have impacted what we did initially...

**Comment by eduardo-rodrigues** [comment]
Precisely my point @jouvin - best to avoid the confusing even though the institute of that person I was referring to is correct. I can try and make a PR later today if nobody does it before ...

**Comment by davidlange6** [comment]
in addition G. Raven's affiliation is incorrect.You probably want to check with the other Nikhef authors.

**Comment by eduardo-rodrigues** [comment]
OK, thanks. From memory he is Nikhef *and* VU. To be checked indeed.

**Comment by davidlange6** [comment]
right - just look in this issue for what he asked us to change...

**Comment by graeme-a-stewart** [comment]
Hi @jouvin - it was the other way around, switching from `xelatex` to `pdflatex`. However, we do have utf-8 options enabled so unicode characters should work, as well as the more traditional tex escape sequences. The way to check is to process the text into the authors.tex then pdflatex the author_stub.tex file.

**Comment by jouvin** [comment]
@davidlange6 I just checked the author list from the arXiv v3 PDF and it looks ok for me. Did I miss something? I just did what @graeme-a-stewart was suggesting:
```
# In documents repository
cd CWP/papers/HSF-CWP-2017-01_roadmap/authors
./a2text.py
pdflatex author_sub.text
```
and as far as I can tell everything seems ok with accents (I don't speek about the MIT/UMass tag or G. Raven's affiliation).

**Comment by jouvin** [comment]
@eduardo-rodrigues BTW, you mention Mark Williams in an earlier comment. If I'm right he is not on the author list. You may want to ask him if this is intentional or just that he missed the CWP or forgot to do it. If I'm right, he is one important person in LHCb software, in particular in trigger and machine learning.

**Comment by eduardo-rodrigues** [comment]
Good point @jouvin. I've just sent Mike Williams an email to see if he wants to support the CWP too.

**Comment by eduardo-rodrigues** [comment]
... he already replied to me and will send the ghost writers an email ...

**Comment by eduardo-rodrigues** [comment]
I think with his update PR !49 is ready.

**Comment by davidlange6** [comment]
so none of the nikhef authors are associated to Amsterdam university?

**Comment by eduardo-rodrigues** [comment]
Gerhard is VU and Marcel Merk is the only one from UvA that I know for sure. The latest list from the LHCb is http://lhcb.web.cern.ch/lhcb/lhcb_page/collaboration/organization/list_of_authors/authors_default.pdf.
Nikhef is special in that it's a kind of consortium among 5 universities.
